# -*- coding: utf-8 -*-
ban = """Agent 版图（母版 shopping-agent=Go购）：①Go购 v2.0 收官，购物主线优先。②雕龙（网文）repo luo080104/diao-long，本地 ~/diaolong；P0 六阶段完成已暂停——重启先读 _tracking-state.json（单一权威事务模型+原子提交+check 校验）；主控流水线：架构→写→质检→内循环 max3→追踪提交；写手 V4-Flash+8铁律+写前守卫+自动备份；量化质检 13 指标；题材黑潮诡异流+验证集《极道天魔》前三章；先 CLI 跑通再套界面；crawler.py 三站交叉校验就绪（公司网络反爬严重，回家再爬）；修 bug 先写复现测试（TDD）。③金融（AI Berkshire）『金融先不做』08-12 确认；五蓝本：AI Berkshire/TradingAgents-Astock/BettaFish/JCP/UZI-Skill。④小布（WorkBuddy）08-14 退役（积分用完），工作由 Pi 接手；已迁移 skills：a-stock-data/macro-monitor/earnings-tracker/humanizer/novel-writing+8 金融 skills。⑤观复见『观复』条。"""

gogou = """Go购 运维与开发规范（2026-08-12/13 定稿）：①agents-radar 日报已部署——10 数据源+DeepSeek 摘要+Server酱推微信，计划任务 AIRadar-Daily 每日 08:30（AutoLearn-GitHub 09:00 是另一套，勿混）；GitHub 凭证在 C:\\Users\\luoji\\agents-radar\\.env。②Langfuse 已接入（@observe 走 shared/llm.py，key 在 shopping-agent/.env，无 key 自动降级不报错）。③shared/ 包（browser_pool/db/llm/llm_usage/notify）三 Agent 共用基础层，Go购 src/ 渐进迁移暂不动。④流程：新功能大改先出 spec 入 SYNC.md 等确认（SDD）；改文件前先备份 ~/.pi/original/；共享文档必含『距上次共享以来的工作』；JS 改动必须浏览器级扫描 9 页面全检——引号嵌套/裸换行是高频 JS 坑（脚本整块不执行）。⑤ruff：.ruff.toml 只留 F+I+部分 RUF，安全交 semgrep。⑥结构：src/app.py 仅 FastAPI+中间件+挂载，路由 src/routes/{search,api,pages}.py，共享符号 src/app_state.py 破循环 import；SSE 前端指数退避重连；user_preferences 有 source/confidence 列（LLM=0.7 手动=1.0）；动态内容从 system 挪到 user 省 57% 成本。⑦浏览器池：预热 4 隐藏浏览器（9300-9303）复用 tab；严格隐藏 set.window.hide()（ctypes 兜底）+延迟 rehide；headless 仅淘宝（tb_profile_h），唯品会/拼多多有头隐藏；并发锁 serialize；清理 taskkill 按 PID+查端口（不能 wmic）。⑧LLM 成本护栏 budget_ok() 每日 ¥3 上限，5 调用点（llm_parse/guide/compare/extract_products/sentiment）超限回退；import 必须模块顶部（局部 import 晚于使用 F821）。⑨family_pin（08-13 用户批准）。"""

jiao = """交互与教训：甲方-乙方——用户是甲方(小白)、Pi 总开发工程师；金融知识只给通识参考，最终决策以甲方为准(风险甲方担)；自信但不自负、不确定直说、一次只问最关键一两个问题；硬指令：不允许查看观复内部系统操作指南；MVP 严格单 Agent(Bull/Bear、四大师二期/三期)；Go购 12 条教训继承为开发红线；产出调整必交用户确认。用户交互：确认疑问后通常给简短指令(『继续』『好的』『开工』『先补上』『做一下吧』)持续推进；重视『判定≠落地』——判定后不落地会被提醒；案例精读须保持『读代码→核验数据→对照书/定案/投资视角→落地→提交』闭环。技术教训：测试隔离——portfolio.py EVENTS_FILE 模块级路径曾致测试写真实账本(143条假交易混入)，事件写入须跟随实例路径(已修+清理)；MCP/数据核验——bond_zh_cov 现70%价格=100占位(无成交/未上市，非代码bug)，修复=过滤价=100占位+bond_cov_comparison 优先+多源 fallback(310只真实)；东财 push2his/push2 对代理 127.0.0.1:7890 间歇封锁(直连+代理都断)，须代理绕过+重试。"""

draft = """观复总纲(08-13~16 六轮问答拍板，『思路』非『锁定向』，更优可换但需确认)：定位=价值投资主线+技术分析辅助+超级鹿鼎公助力(≤20%跟随)；执行=半自动(AI带理由+讲解→用户确认→恒泰手动→双轨记账)；策略分层(父母理念=战略层一票否决/预置=战术层回测后启用)；资产 A股/基金(练手)/可转债/货基/逆回购/打新债/黄金(盯价+讲解)/REITs(二期)；资金<10万，目标年化15-20%，沪深300基准，晨报9:00；真钱2-3万起步，虚拟盘10万(4周跑赢基准或3月→真钱)，虚拟盘阶段即上最便宜云服务器(2核2G 30-50元/月)，真钱阶段必上；MVP 单用户(家人共享二期)；打新债 A 版(日历+分析+提醒，恒泰手动不下单)；推送 MVP=企业微信+网页配置页(复用Go购)，桌面应用(Wails/Tauri)二期，小程序后置。技术 v2.0 定稿(docs/观复技术方案.md+观复规划.md+研讨20问.docx，开发前必读)：五层架构(数据→策略→风险→信号→确认→推送)+FastAPI 直写 MVP(Agent底座二期)+数据层 a-stock-data(akshare 统一+baostock 主源+mootdx，tushare 付费路径，Wind/聚宽排除)+策略库16 YAML(core_rules 规则分离)+RSI 三重组合+利率校准估值+3-5只集中组合+大V 数据驱动权重+回测规范(后复权统一/幸存者偏差/防未来函数 t-1/止损敏感性)+虚拟盘=流程+纪律验证(收益归回测)+里程碑 M1 数据+回测→M2 策略+虚拟盘→M3 推送+确认闭环。图像双通道：TA-Lib 数值形态(MVP)+VL 视觉(二期 Qwen2.5-VL-7B)，一致才发信号。大V 方案(08-14 拍板)：vpush 自动为主(书60+清单)+微博 weibo-cli(OAuth)+雪球 xueqiu-scraper+鹿鼎公≤20%跟随(全披露)+ProxyCat 备胎；连漏2天→切 scraper。git：tb_profile_h 等已 .gitignore+filter-repo。数据边界(08-15 v8)：价格回测10年(2016起，覆盖2018熊/2020抱团/2021-24调整)；估值百分位=全窗口(baostock 2006起)；财务 akshare 约10年；baostock 估值/历史主源(免费无限流/后复权/SQLite 增量缓存+缺段补拉，命中0.5s)，百度降级，腾讯行情主源；全 API 无浏览器依赖——大V 调仓唯一浏览器依赖(vpush 未部署)；tushare 积分版解决90%结构化数据，但大V实操/舆情/知识花钱买不到，交叉验证永远需要。
验证/测评/落地(08-15/16)：回测框架修复 c941522——原 _simulate 严格匹配+pos 占用致买入信号全丢(39 BUY 成交1笔，97%丢失)；修复=顺延<=+涨跌停不可成交(±10%)+建仓前 SELL 跳过+4周有效期；B3 重跑定案：训练78.9%(N=38)/验证80.3%(N=56)。书规则验证 verify_book_rules.py——日线/周线索引对齐 bug 曾致 A/C 判定翻转(重大教训)，切 baostock+10年参数化；结论：A 打五折暂缓(样本=2油股/1.5年/不独立)，C 极端低估(PE<10)支持(N=388 胜率84% 均+25.1%)，M 66%分段维持否定，F/H 待 Q11。06批精读收官：5对照+市场覆盖度(修周线年化 bug×√52)+可转债核验+资金流+回测引擎+数据质量(节假日误报→交易日历修复)→Q11 清单+补读(5分析师/8因子/T+1)；12测试、pyright 清零、4真 bug。测评整改：attribution 加 Alpha>0(防押对板块误判)+signal_ledger.online_score 在线评分(连续2月下滑>10pt 漂移标记)+tushare付费评估.md(验证期后买)。落地：P0+P1 完成(sell_rules.yaml S1-S7、ledger_parse 对话式记账)，v1 MVP 五项齐(数据/策略/虚拟盘/Server酱推送/讲解)；lhb_scorer 5维(Top10 次日+4.03% vs 末10 -3.06%)、etf_screener、可转债13策略、risk_engine、M1.5 策略引擎；虚拟盘开跑(用户确认3信号)：10万买太保/平安/中信 22.3%仓(portfolio.json+events.jsonl)，3月后回填；EasyTrader 不支持恒泰→手动正确；战略9条+战术B3/S2；推送配置页 8201。周报双版(08-16)：文本 v2(KPI 面板)+HTML(weekly_report_html.py，Bento+ECharts)——gf_web /weekly 路由(须在 __main__ 块前，曾 404)；每周五 15:30 自动推送。"""

print("版图:", len(ban))
print("Go购:", len(gogou))
print("交互:", len(jiao))
print("观复草稿:", len(draft))
print("总和(草稿):", len(ban)+len(gogou)+len(jiao)+len(draft))
